import type { ScreenData } from '../../api/client';
import { formatScreenId } from '../../utils/formatters';
import { getScreenRenderUrl, BASE_WIDTH, BASE_HEIGHT } from '../../utils/screenRenderUrl';

interface ScreenRendererProps {
  screen: ScreenData;
  chapterNum: number;
  scale?: number;
  showOverlay?: boolean;
  showInfo?: boolean;
  selected?: boolean;
  onClick?: () => void;
}

export function ScreenRenderer({
  screen,
  chapterNum,
  scale = 1,
  showOverlay = false,
  showInfo = false,
  selected = false,
  onClick,
}: ScreenRendererProps) {
  // Use API scale of 1 (gives 512x384), then CSS scale for display
  const apiScale = 1;
  const renderUrl = getScreenRenderUrl(
    chapterNum,
    screen.index,
    apiScale,
    screen.top_tiles,
    screen.bottom_tiles,
    screen.datapointer,
    screen.worldscreen_color
  );
  const screenId = formatScreenId(screen.index, screen.global_index, chapterNum);

  // Display dimensions - scale from base size
  const displayWidth = BASE_WIDTH * scale;
  const displayHeight = BASE_HEIGHT * scale;

  return (
    <div
      className={`relative inline-block cursor-pointer transition-all ${
        selected ? 'ring-2 ring-yellow-400 z-10' : 'hover:ring-2 hover:ring-white/50'
      }`}
      style={{
        width: displayWidth,
        height: displayHeight,
        backgroundColor: getGroundColor(screen.worldscreen_color),
      }}
      onClick={onClick}
      title={screenId.full}
    >
      {/* Rendered screen image from API */}
      <img
        src={renderUrl}
        alt={`Screen ${screen.index}`}
        draggable={false}
        className="w-full h-full object-cover"
        style={{ imageRendering: 'pixelated' }}
        onError={(e) => {
          // Fallback to a colored div if rendering fails
          e.currentTarget.style.display = 'none';
          const fallback = e.currentTarget.nextElementSibling as HTMLElement;
          if (fallback) fallback.style.display = 'flex';
        }}
      />

      {/* Fallback colored div */}
      <div
        className="absolute inset-0 items-center justify-center text-white text-xs font-bold hidden"
        style={{
          backgroundColor: getParentWorldColor(screen.parent_world),
        }}
      >
        {screen.index.toString(16).toUpperCase()}
      </div>

      {/* Overlay with screen index */}
      {showOverlay && (
        <div className="absolute inset-0 bg-black/40 flex items-center justify-center">
          <span className="text-white font-mono text-sm font-bold drop-shadow-lg">
            {screenId.compact}
          </span>
        </div>
      )}

      {/* Info panel */}
      {showInfo && (
        <div className="absolute bottom-0 left-0 right-0 bg-black/80 text-white text-[8px] p-1 font-mono">
          <div>{screenId.short}</div>
          <div>DP:{screen.datapointer} Top:{screen.top_tiles.toString(16).toUpperCase()}</div>
          <div>Bot:{screen.bottom_tiles.toString(16).toUpperCase()} OS:{screen.objectset}</div>
        </div>
      )}
    </div>
  );
}

// Static pre-rendered thumbnail URL (generated by util/generate-screen-thumbnails.py)
function getScreenStaticUrl(chapterNum: number, screenIndex: number): string {
  return `/assets/screens/ch${chapterNum}/${screenIndex}.png`;
}

// Mini version for overview grids - uses pre-rendered static thumbnails with
// live API as fallback (for post-randomization state when ROM is loaded).
export function ScreenMini({
  screen,
  chapterNum,
  size = 64,
  selected = false,
  onClick,
  showIndex = true,
  tileOpacity = 1,
}: {
  screen: ScreenData;
  chapterNum: number;
  size?: number;
  selected?: boolean;
  onClick?: () => void;
  showIndex?: boolean;
  /** Opacity 0-1 of the rendered tile graphics (0 = hide, only background+index visible) */
  tileOpacity?: number;
}) {
  // Primary: pre-rendered static PNG served from CDN (no backend needed).
  // Fallback: live API render (used if static is missing or after ROM loaded).
  const staticUrl = getScreenStaticUrl(chapterNum, screen.index);
  const apiUrl = getScreenRenderUrl(
    chapterNum,
    screen.index,
    2, // scale=2 matches the pre-rendered thumbnails
    screen.top_tiles,
    screen.bottom_tiles,
    screen.datapointer,
    screen.worldscreen_color
  );
  const screenId = formatScreenId(screen.index, screen.global_index, chapterNum);

  // Aspect ratio: 512x384 base (4:3)
  const width = size;
  const height = Math.round(size * (BASE_HEIGHT / BASE_WIDTH));

  return (
    <div
      className={`relative cursor-pointer transition-all ${
        selected ? 'ring-2 ring-yellow-400 z-10' : 'hover:ring-1 hover:ring-white/50'
      }`}
      style={{
        width,
        height,
        backgroundColor: 'transparent',
      }}
      onClick={onClick}
      title={screenId.full}
    >
      {tileOpacity > 0 && (
        <img
          // Edited screens render live from the in-memory ROM (cache-busted via
          // the t/b/d params in apiUrl); unedited screens use the fast static
          // thumbnail. Falls through to the live API if a static file is missing.
          src={screen.modified ? apiUrl : staticUrl}
          alt={`Screen ${screenId.short}`}
          draggable={false}
          className="absolute inset-0 w-full h-full object-cover"
          style={{ imageRendering: 'auto', opacity: tileOpacity }}
          onError={(e) => {
            // Static thumbnail missing (or live render failed) — try live API render
            const img = e.currentTarget;
            if (img.src !== apiUrl) {
              img.src = apiUrl;
              return;
            }
            // API also failed — show fallback colored div
            img.style.display = 'none';
            const fallback = img.nextElementSibling as HTMLElement;
            if (fallback) fallback.style.display = 'flex';
          }}
        />
      )}
      {/* Fallback colored div when both static and API fail */}
      <div
        className="absolute inset-0 items-center justify-center text-white text-[10px] font-bold hidden"
        style={{ backgroundColor: getParentWorldColor(screen.parent_world) }}
      >
        {screenId.compact}
      </div>
      {/* Screen index overlay - always visible */}
      {showIndex && (
        <div className="absolute top-0 left-0 bg-black/70 text-white text-[8px] font-mono px-1 leading-tight">
          {screenId.compact}
        </div>
      )}
    </div>
  );
}

// Ground color based on WorldScreen color value (from TMOS_Romhack1)
function getGroundColor(wsColorValue: number): string {
  const hex = wsColorValue.toString(16).toUpperCase().padStart(2, '0');
  switch (hex) {
    case '21': case '2A': case '32': case '45':
      return 'rgb(0, 60, 20)';      // past
    case '30': case '3B':
      return 'rgb(0, 112, 236)';    // water
    case '25': case '41': case '47':
      return 'rgb(252, 228, 160)';  // desert
    case '1A':
      return 'rgb(0, 80, 0)';       // dark palace
    case '3C': case '31':
      return 'rgb(164, 0, 0)';      // red
    case '23': case '2B': case '39':
      return 'rgb(188, 188, 188)';  // winter
    case '11': case '27': case '43': case '44': case '4A': case '34': case '1F': case '20':
      return 'rgb(0, 0, 0)';        // black
    case '1C': case '46': case '48':
      return 'rgb(216, 40, 0)';     // lava
    default:
      return 'rgb(0, 148, 0)';      // default green
  }
}

function getParentWorldColor(parentWorld: number): string {
  const colors: Record<number, string> = {
    0x00: '#2563eb', // Overworld - blue
    0x01: '#16a34a', // Town - green
    0x02: '#dc2626', // Dungeon - red
    0x03: '#9333ea', // Maze - purple
    0x04: '#f59e0b', // Special - amber
    0x05: '#06b6d4', // Boss - cyan
  };
  return colors[parentWorld] || '#64748b';
}
