#!/bin/bash
# Disassemble all PRG-ROM banks for The Magic of Scheherazade
# Each bank is 8KB

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
BASE_DIR="$(dirname "$SCRIPT_DIR")"
PRG_ROM="$BASE_DIR/prg-rom.bin"
OUTPUT_DIR="$BASE_DIR/output"
BANK_DIR="$OUTPUT_DIR/banks"
DA65="$BASE_DIR/tools/bin/da65.exe"
CONFIG_DIR="$BASE_DIR/config"

mkdir -p "$BANK_DIR"

echo "=============================================="
echo "The Magic of Scheherazade - Disassembly"
echo "=============================================="
echo ""

# Bank size
BANK_SIZE=8192  # 8KB per bank

# Total banks
TOTAL_BANKS=16

echo "PRG-ROM: $PRG_ROM"
echo "Output:  $BANK_DIR"
echo ""

# Generate disassembly for each bank
for ((i=0; i<TOTAL_BANKS; i++)); do
    BANK_NUM=$(printf "%02d" $i)
    BANK_OFFSET=$((i * BANK_SIZE))

    # Determine CPU address based on bank position
    # Banks 0-13: Switchable, disassemble at $8000
    # Bank 14: Fixed at $C000
    # Bank 15: Fixed at $E000 (contains vectors)
    if [ $i -eq 14 ]; then
        CPU_ADDR="\$C000"
        CPU_ADDR_DEC=49152
    elif [ $i -eq 15 ]; then
        CPU_ADDR="\$E000"
        CPU_ADDR_DEC=57344
    else
        CPU_ADDR="\$8000"
        CPU_ADDR_DEC=32768
    fi

    echo "Bank $BANK_NUM: offset 0x$(printf '%05X' $BANK_OFFSET), CPU addr $CPU_ADDR"

    # Extract bank to temp file
    TEMP_BANK="$BANK_DIR/bank_${BANK_NUM}.bin"
    dd if="$PRG_ROM" of="$TEMP_BANK" bs=1 skip=$BANK_OFFSET count=$BANK_SIZE 2>/dev/null

    # Create bank-specific info file
    INFO_FILE="$BANK_DIR/bank_${BANK_NUM}.info"
    cat > "$INFO_FILE" << EOF
# da65 info file for Bank $BANK_NUM
GLOBAL {
    STARTADDR    $CPU_ADDR_DEC;
    CPU          "6502";
    COMMENTS     2;
};

# NES Hardware Registers
LABEL { NAME "PPU_CTRL";       ADDR \$2000; };
LABEL { NAME "PPU_MASK";       ADDR \$2001; };
LABEL { NAME "PPU_STATUS";     ADDR \$2002; };
LABEL { NAME "OAM_ADDR";       ADDR \$2003; };
LABEL { NAME "OAM_DATA";       ADDR \$2004; };
LABEL { NAME "PPU_SCROLL";     ADDR \$2005; };
LABEL { NAME "PPU_ADDR";       ADDR \$2006; };
LABEL { NAME "PPU_DATA";       ADDR \$2007; };
LABEL { NAME "OAM_DMA";        ADDR \$4014; };
LABEL { NAME "APU_STATUS";     ADDR \$4015; };
LABEL { NAME "JOY1";           ADDR \$4016; };
LABEL { NAME "JOY2_FRAME";     ADDR \$4017; };
EOF

    # Add vector labels for bank 15
    if [ $i -eq 15 ]; then
        cat >> "$INFO_FILE" << EOF

# Interrupt Vectors
LABEL { NAME "NMI_Handler";    ADDR \$E3C9; };
LABEL { NAME "RESET_Handler";  ADDR \$E19B; };
RANGE { START \$FFFA; END \$FFFF; TYPE ByteTable; };
LABEL { NAME "Vector_NMI";     ADDR \$FFFA; };
LABEL { NAME "Vector_RESET";   ADDR \$FFFC; };
LABEL { NAME "Vector_IRQ";     ADDR \$FFFE; };
EOF
    fi

    # Run da65
    OUTPUT_ASM="$BANK_DIR/bank_${BANK_NUM}.asm"
    "$DA65" -i "$INFO_FILE" -o "$OUTPUT_ASM" "$TEMP_BANK"

    # Add header comment to output
    TEMP_ASM=$(mktemp)
    cat > "$TEMP_ASM" << EOF
; ============================================================================
; The Magic of Scheherazade - Bank $BANK_NUM Disassembly
; ============================================================================
; File Offset: 0x$(printf '%05X' $BANK_OFFSET) - 0x$(printf '%05X' $((BANK_OFFSET + BANK_SIZE - 1)))
; CPU Address: $CPU_ADDR - \$$(printf '%04X' $((CPU_ADDR_DEC + BANK_SIZE - 1)))
; Size: 8192 bytes (8 KB)
; ============================================================================
;
; NOTE: This is a raw disassembly. Data regions interpreted as code will
; appear as garbage instructions. Further analysis needed to identify
; code vs data boundaries.
;
; ============================================================================

EOF
    cat "$OUTPUT_ASM" >> "$TEMP_ASM"
    mv "$TEMP_ASM" "$OUTPUT_ASM"

    # Remove temp bank file
    rm "$TEMP_BANK"
done

echo ""
echo "Generating combined full disassembly..."

# Combine all banks into single file
FULL_ASM="$OUTPUT_DIR/full_disassembly.asm"
cat > "$FULL_ASM" << 'EOF'
; ============================================================================
; The Magic of Scheherazade - Complete PRG-ROM Disassembly
; ============================================================================
;
; ROM Information:
;   PRG-ROM: 128 KB (16 x 8KB banks)
;   CHR-ROM: 128 KB (graphics, not included)
;   Mapper:  1 (MMC1 / SxROM)
;
; Bank Layout:
;   Banks 00-13: Switchable, mapped to $8000-$9FFF
;   Bank 14:     Fixed at $C000-$DFFF
;   Bank 15:     Fixed at $E000-$FFFF (contains vectors)
;
; Entry Points:
;   RESET: $E19B
;   NMI:   $E3C9
;   IRQ:   $E19B
;
; Generated by da65 (cc65 suite)
; ============================================================================

EOF

for ((i=0; i<TOTAL_BANKS; i++)); do
    BANK_NUM=$(printf "%02d" $i)
    echo "" >> "$FULL_ASM"
    echo "; ============================================================================" >> "$FULL_ASM"
    echo "; BANK $BANK_NUM" >> "$FULL_ASM"
    echo "; ============================================================================" >> "$FULL_ASM"
    cat "$BANK_DIR/bank_${BANK_NUM}.asm" >> "$FULL_ASM"
done

echo "Done!"
echo ""
echo "Output files:"
echo "  Full disassembly: $FULL_ASM"
echo "  Individual banks: $BANK_DIR/bank_XX.asm"
